apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coderprabhu-ui
  name: coderprabhu-ui-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coderprabhu-ui
      tier: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: coderprabhu-ui
        tier: web
    spec:
      containers:
        - image: gcr.io/all-projects-292200/github.com/coderprabhu/coderprabhu-ui
          imagePullPolicy: IfNotPresent
          name: coderprabhu-ui-app
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 24Mi
